config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'pages/about'

  get 'pages/contact'

  resources :bunks
  get 'bunks/new' => 'bunks#new', :as => :new_modal

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    user ||= User.new
    can :manage, Bunk, user_id: user.id
  end
end

app/models/bunk.rb
class Bunk < ActiveRecord::Base
	validates_presence_of :subjectname, :bunk, :total
	validates_uniqueness_of :subjectname

	belongs_to :user
	validates_presence_of :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bunks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bunks_controller.rb
class BunksController < ApplicationController
  load_and_authorize_resource

  before_action :set_bunk, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js
  def index
    @bunks = Bunk.all
    respond_with(@bunks)
  end

  def show
  end

  def new
    @bunk = Bunk.new
    respond_with(@bunk)
  end

  def edit
    respond_with @bunk do |format|
      format.html { redirect_to bunks_path }
    end
  end

  def create
    @bunk = Bunk.new(bunk_params)
    @bunk.user = current_user
    @bunk.save
    respond_with @bunk do |format|
      format.html { redirect_to bunks_path }
    end
  end

  def update
    @bunk.update(bunk_params)
    respond_with @bunk do |format|
      format.html { redirect_to bunks_path }
    end
  end

  def destroy
    @bunk.destroy
    respond_with(@bunk)
  end

  private
    def set_bunk
      @bunk = Bunk.find(params[:id])
    end

    def bunk_params
      params.require(:bunk).permit(:subjectname, :bunk, :total, :comments)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bunks_helper.rb
module BunksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bunks/_form.html.erb
<%= simple_form_for(@bunk) do |f| %>
  <%= f.input :subjectname, label: 'Subject Name' %>
  <%= f.input :bunk, label: 'Bunk' %>
  <%= f.input :total, label: 'Total' %>
  <%= f.input :comments, label: 'Comments' %>
  <%= f.button :submit, class: 'button small radius success' %>

<% end %>

app/views/bunks/_show.html.erb
<p>
  <strong>Subject Name:</strong>
  <%= @bunk.subjectname %>
</p>

<p>
  <strong>Bunk:</strong>
  <%= @bunk.bunk %>
</p>

<p>
  <strong>Total:</strong>
  <%= @bunk.total %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @bunk.comments %>
</p>

<div id="edit_modal" class="reveal-modal" data-reveal></div>
<%= link_to 'Edit', edit_bunk_path(@bunk), class:'button radius', 'data-reveal-id' => 'edit_modal', :remote => true %>

app/views/bunks/edit.js.erb
$('#edit_modal').html("<%= j (render 'form', :locals => {:bunk => @bunk }) %><a class='close-reveal-modal'>&#215;</a>");
$('#edit_modal').foundation('reveal','open');

app/views/bunks/index.html.erb
<h1>Listing bunks</h1>
      
      <div id="new_modal" class="reveal-modal" data-reveal></div>
      <div id="edit_modal" class="reveal-modal" data-reveal></div>
      <div id="show_modal" class="reveal-modal" data-reveal></div>

      <table>
        <thead>
          <tr>
            <th width="20%">Subject Name</th>
            <th>Present</th>
            <th>Total</th>
            <th>Bunk</th>
            <th>Percentage</th>
            <th width="12%"><b style="color:red">To Attend</b><br/>or<br/><b style="color:green">Can Bunk</b></th>
            <th colspan="9"></th>
          </tr>
        </thead>

        <tbody>
          <% @total_bunk = 0 %><% @total_total = 0 %><% @total_present = 0 %><% @total_percentage = 0.0 %>
          <% @total_classes = 0 %>
          <% @bunks.each do |bunk| %>
            <% if bunk.user_id == current_user.id %>
              <tr>
                <% @_bunk = bunk.bunk %><% @total_bunk = @total_bunk + @_bunk %>
                <% @_total = bunk.total %><% @total_total = @total_total + @_total %>
                <% @_present =  @_total - @_bunk %><% @total_present = @total_present + @_present %>
                <% @_percentage = ((@_present.to_f*100)/@_total.to_f).round(2) %>
                <% @_subject = bunk.subjectname %> 
                <td><%=  @_subject %></td>
                <td><%= @_present %></td>
                <td><%= @_total %></td>
                <td><%= @_bunk %></td>
                <td class="<%= @_percentage<80.0 ? 'red' : 'green' %>"><%= @_percentage %>%</td>
                <% if @_percentage<=80.0 %>
                  <% (1..100).each do |i| %>
                    <% if (((@_present+i).to_f*100)/(@_total+i).to_f) >= 80.00%>
                      <% @classes = i %>
                      <% break %>
                    <% end %>
                  <% end %>
                <% else %>
                  <% (1..100).each do |i| %>
                    <% if (((@_present).to_f*100)/(@_total+i).to_f) < 80.00 %>
                      <% @classes = i %>
                      <% break %>
                    <% end %>
                  <% end %>
                <% end %>
                <td class="<%= @_percentage<80.0 ? 'red' : 'green' %>"><%= @classes %></td>
                <td width="30%"> 
                  <%= link_to 'Show', bunk_path(bunk), class:'button tiny radius secondary', 'data-reveal-id' => 'show_modal', :remote => true  %>
                  <%= link_to 'Edit', edit_bunk_path(bunk), class:'button tiny radius', 'data-reveal-id' => 'edit_modal', :remote => true %>
                  <%= link_to 'Destroy', bunk, method: :delete, data: { confirm: 'Are you sure?' }, class:'button tiny radius alert' %>
                </td>
              </tr>
            <% end %>
          <% end %>
              <tr>
                <td><b>TOTAL</b></td>
                <td><b><%= @total_present %></b></td>
                <td><b><%= @total_total %></b></td>
                <td><b><%= @total_bunk %></b></td>
                    <% @total_percentage = (@total_present.to_f * 100 / @total_total.to_f).round(2) %>
                <td class="<%= @total_percentage<=80.0 ? 'red' : 'green' %>">
                  <b><%= @total_percentage %>%</b>
                </td>
                <% if @total_percentage<=80.0 %>
                  <% (1..100).each do |i| %>
                    <% if (((@total_present+i).to_f*100)/(@total_total+i).to_f) >= 80.00%>
                      <% @total_classes = i %>
                      <% break %>
                    <% end %>
                  <% end %>
                <% else %>
                  <% (1..100).each do |i| %>
                    <% if (((@total_present).to_f*100)/(@total_total+i).to_f) < 80.00 %>
                      <% @total_classes = i %>
                      <% break %>
                    <% end %>
                  <% end %>
                <% end %>
                <td class="<%= @total_percentage<=80.0 ? 'red' : 'green' %>"><%= @total_classes %></td>
                <td></td>
              </tr>
        </tbody>
      </table>

      <%= link_to 'New Bunk', new_bunk_path, class: 'button small radius secondary', 'data-reveal-id' => 'new_modal', :remote => true %>
<br>

  

app/views/bunks/new.html.erb
<div id="newModal" class="reveal-modal" data-reveal>

</div>

app/views/bunks/new.js.erb
$('#new_modal').html("<%= j (render 'form') %><a class='close-reveal-modal'>&#215;</a>");
$('#new_modal').foundation('reveal','open');

app/views/bunks/show.js.erb
$('#show_modal').html("<%= j (render 'show', :locals => {:bunk => @bunk }) %><a class='close-reveal-modal'>&#215;</a>");
$('#show_modal').foundation('reveal','open');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Bunk Zilla" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><span><%= link_to 'Home', root_url %></span></h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"></li>
      </ul>

     <section class="top-bar-section">
      <ul class="left">
        <li class="divider"></li>
        <li>
          <%= link_to 'Bunks', bunks_url %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to 'About', pages_about_url %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to 'Contact', pages_contact_url %>
        </li>
        <li class="divider"></li>
      </ul>
      <ul class="right">
        <% if user_signed_in? %>
          <li class="divider"></li>
          <li>
            <%= link_to current_user.email, "#" %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
          </li>
        <% else %>
          <li class="divider"></li>
          <li>
            <%= link_to "Sign In", new_user_session_path %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to "Sign Up", new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </section>
    </nav>
    <div class="row">
        <div class="large-10 large-offset-2 columns-3">
            <%= yield %>
        </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
              <div data-alert class="alert-box success radius">
                <%= current_user.email %> has successfully logged in!
                <a href="#" class="close">&times;</a>
              </div>
<% end %>
<h1>Pages#home</h1>
	<p>Find me in app/views/pages/home.html.erb</p>	